#!/bin/bash

monitor_name=$1

brightness=$(xrandr --verbose --current | awk "/$monitor_name connected/ { flag=1; next; } /Brightness/{ if(flag==1) { gsub(\"	Brightness: \", \"\"); print; exit; } }")

echo ${brightness}